version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  app:
    depends_on:
      - mysql
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  mysql: